//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReference1.zws_posteo_correcciones")]
    public interface zws_posteo_correcciones
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse1 ZMF_POSTEO_CORRECCIONES(ServiceReference1.ZMF_POSTEO_CORRECCIONESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse1> ZMF_POSTEO_CORRECCIONESAsync(ServiceReference1.ZMF_POSTEO_CORRECCIONESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMF_POSTEO_CORRECCIONES
    {
        
        private ZST_COR_CREADAS[] t_LOG_DOC_CREADOSField;
        
        private ZST_LOG_ERRORES[] t_LOG_ERRORESField;
        
        private ZST_DOC_CORRECCIONES[] zTB_POSTEOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_COR_CREADAS[] T_LOG_DOC_CREADOS
        {
            get
            {
                return this.t_LOG_DOC_CREADOSField;
            }
            set
            {
                this.t_LOG_DOC_CREADOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_LOG_ERRORES[] T_LOG_ERRORES
        {
            get
            {
                return this.t_LOG_ERRORESField;
            }
            set
            {
                this.t_LOG_ERRORESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_DOC_CORRECCIONES[] ZTB_POSTEO
        {
            get
            {
                return this.zTB_POSTEOField;
            }
            set
            {
                this.zTB_POSTEOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_COR_CREADAS
    {
        
        private string fACTURAField;
        
        private string dOC_CONTABLEField;
        
        private string nCFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FACTURA
        {
            get
            {
                return this.fACTURAField;
            }
            set
            {
                this.fACTURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_CONTABLE
        {
            get
            {
                return this.dOC_CONTABLEField;
            }
            set
            {
                this.dOC_CONTABLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NCF
        {
            get
            {
                return this.nCFField;
            }
            set
            {
                this.nCFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_DOC_CORRECCIONES
    {
        
        private string sOCIEDADField;
        
        private string pEDIDOField;
        
        private string cOD_CLIENTEField;
        
        private string nOMBREField;
        
        private string cEDULAField;
        
        private string tIPO_PEDIDOField;
        
        private string fECH_DOCUMENTOField;
        
        private string nCF_NUEVOField;
        
        private string nCF_ORIGENField;
        
        private string mATERIALField;
        
        private string uNI_MEDIDAField;
        
        private string cANTIDADField;
        
        private decimal aMOU_GROSSField;
        
        private string dISC_EPDField;
        
        private string dISC_VOLField;
        
        private decimal tAX_ITBISField;
        
        private decimal tAX_ISCField;
        
        private decimal tAX_ISCEField;
        
        private decimal nETOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SOCIEDAD
        {
            get
            {
                return this.sOCIEDADField;
            }
            set
            {
                this.sOCIEDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PEDIDO
        {
            get
            {
                return this.pEDIDOField;
            }
            set
            {
                this.pEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string COD_CLIENTE
        {
            get
            {
                return this.cOD_CLIENTEField;
            }
            set
            {
                this.cOD_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NOMBRE
        {
            get
            {
                return this.nOMBREField;
            }
            set
            {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CEDULA
        {
            get
            {
                return this.cEDULAField;
            }
            set
            {
                this.cEDULAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIPO_PEDIDO
        {
            get
            {
                return this.tIPO_PEDIDOField;
            }
            set
            {
                this.tIPO_PEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FECH_DOCUMENTO
        {
            get
            {
                return this.fECH_DOCUMENTOField;
            }
            set
            {
                this.fECH_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NCF_NUEVO
        {
            get
            {
                return this.nCF_NUEVOField;
            }
            set
            {
                this.nCF_NUEVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NCF_ORIGEN
        {
            get
            {
                return this.nCF_ORIGENField;
            }
            set
            {
                this.nCF_ORIGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string UNI_MEDIDA
        {
            get
            {
                return this.uNI_MEDIDAField;
            }
            set
            {
                this.uNI_MEDIDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CANTIDAD
        {
            get
            {
                return this.cANTIDADField;
            }
            set
            {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal AMOU_GROSS
        {
            get
            {
                return this.aMOU_GROSSField;
            }
            set
            {
                this.aMOU_GROSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string DISC_EPD
        {
            get
            {
                return this.dISC_EPDField;
            }
            set
            {
                this.dISC_EPDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DISC_VOL
        {
            get
            {
                return this.dISC_VOLField;
            }
            set
            {
                this.dISC_VOLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal TAX_ITBIS
        {
            get
            {
                return this.tAX_ITBISField;
            }
            set
            {
                this.tAX_ITBISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal TAX_ISC
        {
            get
            {
                return this.tAX_ISCField;
            }
            set
            {
                this.tAX_ISCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal TAX_ISCE
        {
            get
            {
                return this.tAX_ISCEField;
            }
            set
            {
                this.tAX_ISCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal NETO
        {
            get
            {
                return this.nETOField;
            }
            set
            {
                this.nETOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_LOG_ERRORES
    {
        
        private string mSJ_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MSJ_ERROR
        {
            get
            {
                return this.mSJ_ERRORField;
            }
            set
            {
                this.mSJ_ERRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMF_POSTEO_CORRECCIONESResponse
    {
        
        private ZST_COR_CREADAS[] t_LOG_DOC_CREADOSField;
        
        private ZST_LOG_ERRORES[] t_LOG_ERRORESField;
        
        private ZST_DOC_CORRECCIONES[] zTB_POSTEOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_COR_CREADAS[] T_LOG_DOC_CREADOS
        {
            get
            {
                return this.t_LOG_DOC_CREADOSField;
            }
            set
            {
                this.t_LOG_DOC_CREADOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_LOG_ERRORES[] T_LOG_ERRORES
        {
            get
            {
                return this.t_LOG_ERRORESField;
            }
            set
            {
                this.t_LOG_ERRORESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_DOC_CORRECCIONES[] ZTB_POSTEO
        {
            get
            {
                return this.zTB_POSTEOField;
            }
            set
            {
                this.zTB_POSTEOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMF_POSTEO_CORRECCIONESRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.ZMF_POSTEO_CORRECCIONES ZMF_POSTEO_CORRECCIONES;
        
        public ZMF_POSTEO_CORRECCIONESRequest()
        {
        }
        
        public ZMF_POSTEO_CORRECCIONESRequest(ServiceReference1.ZMF_POSTEO_CORRECCIONES ZMF_POSTEO_CORRECCIONES)
        {
            this.ZMF_POSTEO_CORRECCIONES = ZMF_POSTEO_CORRECCIONES;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMF_POSTEO_CORRECCIONESResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse ZMF_POSTEO_CORRECCIONESResponse;
        
        public ZMF_POSTEO_CORRECCIONESResponse1()
        {
        }
        
        public ZMF_POSTEO_CORRECCIONESResponse1(ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse ZMF_POSTEO_CORRECCIONESResponse)
        {
            this.ZMF_POSTEO_CORRECCIONESResponse = ZMF_POSTEO_CORRECCIONESResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface zws_posteo_correccionesChannel : ServiceReference1.zws_posteo_correcciones, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class zws_posteo_correccionesClient : System.ServiceModel.ClientBase<ServiceReference1.zws_posteo_correcciones>, ServiceReference1.zws_posteo_correcciones
    {
        
        public zws_posteo_correccionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse1 ZMF_POSTEO_CORRECCIONES(ServiceReference1.ZMF_POSTEO_CORRECCIONESRequest request)
        {
            return base.Channel.ZMF_POSTEO_CORRECCIONES(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ZMF_POSTEO_CORRECCIONESResponse1> ZMF_POSTEO_CORRECCIONESAsync(ServiceReference1.ZMF_POSTEO_CORRECCIONESRequest request)
        {
            return base.Channel.ZMF_POSTEO_CORRECCIONESAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
